config/routes.rb
Rails.application.routes.draw do
    get 'home/index'
    root :to => "home#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
    resources :sources
    match 'tagged' => 'posts#tagged', :via => [:get], :as => 'tagged'
    resources :tags, only: [:index, :show]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/author.rb
class Author < ApplicationRecord
    has_and_belongs_to_many :sources
    
    #, :join_table => "authors_sources", :class_name => "Source"
end

app/models/source.rb
class Source < ApplicationRecord
    acts_as_taggable
    acts_as_taggable_on :subjects, :warnings
    has_and_belongs_to_many :authors
    
    #, :join_table => "authors_sources", :class_name => "Author"
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/sources_controller.rb
class SourcesController < ApplicationController
    def index
        @sources = Source.all
    end
    
    def show 
        @id = params[:id]
        @source = Source.find(@id)
    end
    
    def new
        @source = Source.new
    end
    
    def create
        Source.create(source_params)
        redirect_to sources_path
    end
    
    def edit
        @source = Source.find(params[:id])
    end
    
    def update
        source = Source.find(params[:id])
        source.update(source_params)
        redirect_to source_path(source)
    end
    
    def destroy
        source = Source.find(params[:id])
        source.destroy
        redirect_to sources_path
    end
    
    def tagged
        if params[:tag].present?
            @sources = Source.tagged_with(params[:tag])
        else
            @sources = Source.all
        end
    end
    
    def source_params
        params.require(:source).permit(:title, :year, :is_free, :access_link, :site_name, :publication, :additional_info, :description, :tag_list, :subject_list, :warning_list)
    end
        
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/sources_helper.rb
module SourcesHelper
    #include ActsAsTaggableOn::TagsHelper
end

app/views/acts_as_taggable_on/tags/_tag.html.erb
<%= link_to tag.name, tag_path(tag) %>

app/views/home/index.html.erb
<h1>House of Vesta</h1>
<h2>Roman Academia Search</h2>
<p>Yay</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Romansearch</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
      
  </head>

  <body>
      <div class="navigation">
          <div class="center">
              <%= link_to "Sources List", sources_path %>
          </div>
      </div>
      <div class="container">
          <%= yield %>
      </div>
   <div class="footer">
      </div> 
  </body>
</html>

app/views/sources/_source.html.erb
<h4><%= source.title %></h4>
    <%= source.year %>
<%= for source.authors do |f| %>
    <% author_name = f.first_name + " " + f.last_name %>
    <% if f = source.authors.last %>
        <% author_name += ", " %>
    <% end %>
<%= end %>

app/views/sources/edit.html.erb
<h1>Edit a Source:</h1>

<%= form_for(@source) do |f| %>
    <ul>
        <li>
            <%= f.label :title %>
            <%= f.text_field :title %>
        </li>
        <li>
            <%= f.label :year %>
            <%= f.number_field :year %>
        </li>
        <li>
            <%= f.label :access_link %>
            <%= f.text_field :access_link %>
        </li>
        <li>
            <%= f.label :is_free %>
            <%= f.check_box :is_free %>
        </li>
        <li>
            <%= f.label :site_name %>
            <%= f.text_field :site_name %>
        </li>
        <li>
            <%= f.label :publication %>
            <%= f.text_field :publication %>
        </li>
        <li>
            <%= f.label :additional_info %>
            <%= f.text_field :additional_info %>
        </li>
        <li>
            <%= f.label :description %>
            <%= f.text_area :description %>
        </li>
        <li>
            <%= f.label :subjects %>
            <%= f.text_field :subject_list, value: f.object.subject_list.to_s %>
        </li>
    </ul>
<%= f.submit(class: "button") %>
<% end %>

app/views/sources/index.html.erb
<h1>Sources</h1>
<ul>
    <% @sources.each do |source| %>
    <li>
        <%= link_to(source.title, source_path(source)) %>
    </li>
    <% end %>
</ul>

<%= link_to("Add a source!", new_source_path, class: "button") %>

app/views/sources/new.html.erb
<h1>Add a New Source:</h1>

<%= form_for(@source) do |f| %>
    <ul>
        <li>
            <%= f.label :title %>
            <%= f.text_field :title %>
        </li>
        <li>
            <%= f.label :year %>
            <%= f.number_field :year %>
        </li>
        <li>
            <%= f.label :access_link %>
            <%= f.text_field :access_link %>
        </li>
        <li>
            <%= f.label :is_free %>
            <%= f.check_box :is_free %>
        </li>
        <li>
            <%= f.label :site_name %>
            <%= f.text_field :site_name %>
        </li>
        <li>
            <%= f.label :publication %>
            <%= f.text_field :publication %>
        </li>
        <li>
            <%= f.label :additional_info %>
            <%= f.text_field :additional_info %>
        </li>
        <li>
            <%= f.label :description %>
            <%= f.text_area :description %>
        </li>
        <li>
            <%= f.label :subject_tags %>
            <%= f.text_field :subject_list, value: f.object.subject_list.to_s %>
        </li>
    </ul>
<%= f.submit(class: "button") %>
<% end %>

app/views/sources/show.html.erb
<dl>
    <dt>Title:</dt>
        <dd><%= @source.title %></dd>
    <dt>Year:</dt>
        <dd><%= @source.year %></dd>
    <dt>Site name:</dt>
        <dd><%= @source.site_name %></dd>
    <dt>Publication:</dt>
        <dd><%= @source.publication %></dd>
    <dt>Additional Info:</dt>
        <dd><%= @source.additional_info %></dd>
    <dt>Description:</dt>
        <dd><%= @source.description %></dd>
    <dt>Subject Tags:</dt>
    <% @source.subjects.each do |tag| %>
        <dd> <%= link_to tag.name, tagged_url(:tag => tag.name) %></dd>
    <% end %>
</dl>

<%= link_to "Edit Source", edit_source_path(@source), class: "button" %>
<%= link_to("Delete Source", source_path(@source), method: :delete, class: "button danger") %>

app/views/tags/index.html.erb
<h1>Subject Tags:</h1>
<%= render @tags %>

app/views/tags/show.html.erb
<h1><%= @tag.name %></h1>
<div><%= render @sources %></div>